name: Desplegar a Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar a Vercel
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajuste esta versión según sus necesidades

      - name: Instalar dependencias
        run: npm ci

      - name: Desplegar a Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --confirm --token $VERCEL_TOKEN