name: Despliegue Backend a Vercel

on:
  push:
    branches:
      - main

jobs:
  deployment_vercel_Backend:
    runs-on: ubuntu-latest
    environment: production
    # needs: prettier  # Asumiendo que tienes un job 'prettier' previo

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: "Echo values"
        run: |
          echo $VERCEL_PROJECT_ID
          echo $VERCEL_ORG_ID
          echo $VERCEL_TOKEN

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Set Environment Variables
        run: |
          mkdir -p ./server
          echo "PGHOST=${{ secrets.PGHOST }}" > ./server/.env
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> ./server/.env
          echo "PGUSER=${{ secrets.PGUSER }}" >> ./server/.env
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> ./server/.env
          echo "PGPORT=${{ secrets.PGPORT }}" >> ./server/.env
          echo "REACT_APP_AUTH_TOKEN=${{ secrets.REACT_APP_AUTH_TOKEN }}" >> ./server/.env

      - name: Install Vercel CLI
        run: |
          cd ./server
          npm install vercel

      - name: Deploy to Vercel
        run: |
          cd ./server
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} -y