name: Desplegar a Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar a Vercel
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta esta versión según tus necesidades

      - name: Configurar variables de entorno
        run: |
          echo "PGHOST=${{ secrets.PGHOST }}" > ./server/.env
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> ./server/.env
          echo "PGUSER=${{ secrets.PGUSER }}" >> ./server/.env
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> ./server/.env
          echo "PGPORT=${{ secrets.PGPORT }}" >> ./server/.env
          echo "REACT_APP_AUTH_TOKEN=${{ secrets.REACT_APP_AUTH_TOKEN }}" >> ./server/.env

      - name: Instalar dependencias y Vercel CLI
        run: |
          cd ./server
          npm ci
          npm install -g vercel

      - name: Desplegar a Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd ./server
          vercel --prod --token $VERCEL_TOKEN -y